name: sstcam-simulation
channels:
  - conda-forge
  - cta-observatory
dependencies:
  - pip
  - numpy~=1.21
  - scipy
  - astropy
  - pandas
  - numba
  - matplotlib
  - iminuit
  - h5py
  - PyYAML
  - requests
  - tqdm
  - pytest
  - ctapipe~=0.9.0
  - eventio>=1.4.1
