name: sstcam-simulation
channels:
  - conda-forge
dependencies:
  - anaconda-client
  - numpy
  - scipy
  - astropy
  - pandas
  - numba
  - matplotlib
  - iminuit
  - h5py
  - PyYAML
  - tqdm
  - pytest
  - notebook
