name: sstcam-simulation
channels:
  - defaults
  - conda-forge
  - cta-observatory
dependencies:
  - anaconda-client
  - pip
  - numpy
  - scipy
  - astropy
  - pandas
  - numba
  - matplotlib
  - iminuit
  - h5py
  - PyYAML
  - requests
  - tqdm
  - pytest
  - notebook
  - ctapipe~=0.9.0
  - eventio>=1.4.1
  - pip:
      - "--editable=git+https://github.com/sstcam/CHECLabPy#egg=CHECLabPy"
