name: sstcam-simulation
channels:
  - conda-forge
  - cta-observatory
dependencies:
  - python=3.8
  - pip~=24.0.0
  - ipython
  - numpy~=1.22
  - scipy
  - astropy
  - pandas
  - numba
  - matplotlib
  - iminuit
  - h5py
  - PyYAML
  - requests
  - tqdm
  - pytest
