on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

name: tests

jobs:
  build:
    name: TEST (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-13', 'macos-latest']
        python-version: ['3.8']
    steps:
      - name: Setup checkout
        uses: actions/checkout@v2
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
           auto-update-conda: true
           activate-environment: sstcam-simulation
           environment-file: environment.yml
           python-version: ${{ matrix.python-version }}
           auto-activate-base: false
           miniforge-version: latest
      - name: Conda info
        shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Install
        shell: bash -l {0}
        env:
          KONRAD_USERNAME: ${{ secrets.KONRAD_USERNAME }}
          KONRAD_PASSWORD: ${{ secrets.KONRAD_PASSWORD }}
        run: |
          make develop
          python sstcam_simulation/data/__init__.py
      - name: Test
        shell: bash -l {0}
        run: |
          make test
